name: cars_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^7.0.1
  flutter_appauth : ^3.0.1
  http: ^0.13.4
  url_launcher: ^6.3.1
  csv: ^6.0.0
  path_provider: ^2.1.5
  file_picker: ^8.1.3
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
